#!/bin/bash

environment () {

DE=""
DM=""
WM=""
seleccionDE=false
seleccionWM=false
seleccionXORG=false
seleccionTTY=false



cmd=(dialog --keep-tite --no-collapse --cr-wrap --backtitle "${title}" --title "-| Entorno |-" --column-separator "|" --no-tags --ok-label '< Seleccionar >' --nocancel --menu "\nElige una opción\n " 12 50 12)

options=(3 "Emulador de Terminal | (tty)"
         1 "Entorno de escritorio | (DE)"
         2 "Gestor de ventanas | (WM)")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        1) #INICIO (DE)    

seleccionDE=true

cmd=(dialog --keep-tite --no-collapse --cr-wrap --backtitle "${title}" --column-separator "|" --no-tags --ok-label '< Seleccionar >' --menu "\nSelecciona tu escritorio a instalar - (DE)\n " 21 60 21)

options=(1 " > | xfce4 | Xfce desktop| <"
         2 " > | gnome | GNOME Classic desktop| <"
         3 " > | plasma | KDE Plasma desktop| <"
         4 " > | deepin | Deepin desktop| <"
         5 " > | mate | Mate GTK3 desktop| <"
         6 " > | lxqt | LXDE-Qt & Razor-qt projects| <"
         7 " > | lxde | The Lightweight X11 GTK2| <"
         8 " > | lxde-gtk3 | The Lightweight X11 GTK3| <"
         9 " > | budgie-desktop | Budgie desktop| <"
         10 " > | cinnamon | Cinnamon desktop| <"
         11 " > | gnome-flashback | GNOME 2 desktop| <"
         12 " > | enlightenment | Enlightenment desktop| <")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        
###########SELECCION (DE)
        1) #XFCE4

cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags \
--ok-label '< Seleccionar >' --nocancel --menu "\n\
Selecciona una opción para XFCE4 \n " 12 60 20)

options=(1 "   Xfce4                    "
         2 "   Xfce4 - Tema Arcris      ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in

        1)  DE="Xfce4"
            ;;
            
        2)  DE="Xfce4 Arcris"
            ;;
            
    esac
done
        ;;


        2)  #INICIO GNOME
cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags \
--ok-label '< Seleccionar >' --nocancel --menu "\n \
Selecciona una opción para GNOME \n " 12 60 20)

options=(1 "   Gnome || Sistema Completo  "
         2 "   Gnome || Minimalista       "
         3 "   Gnome || Tema Arcris       ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in

        1)  DE="Gnome"
            ;;
            
        2)  DE="Gnome Lite"
            ;;

        3)  DE="Gnome Arcris"
            ;;
            
    esac
done
            ;;
 
        3)  #INICIO KDE
cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags \
--ok-label '< Seleccionar >' --nocancel --menu "\n \
Selecciona una opción para KDE Plasma \n " 12 60 20)

options=(1 "   Plasma || Sistema Completo  "
         2 "   Plasma || Minimalista       ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in

        1)  DE="KDE Plasma"
            ;;
            
        2)  DE="KDE Plasma Lite"
            ;;

    esac
done
            ;;


        4)  #INICIO DEEPIN
            DE="Deepin"
            ;;

        5)  #INICIO MATE
            DE="MATE"
            ;;

        6)  #INICIO LXQt
            DE="LXQt"
            ;;

        7)  #INICIO LXDE
            DE="LXDE"
            ;;

        8)  #INICIO LXDE GTK3
            DE="LXDE GTK3"
            ;;

        9)  #INICIO Budgie
            DE="Budgie"
            ;;

        10)  #INICIO Cinnamon
            DE="Cinnamon"
            ;;

        11)  #INICIO GNOME 2
            DE="GNOME 2"
            ;;

        12)  #INICIO Enlightenment
            DE="Enlightenment"
            ;;


    esac
done
            ;;
#########FIN ESCRITORIO


        2) #INICIO (WM)
seleccionWM=true

cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags --ok-label '  Seleccionar  ' --menu "\nSelecciona tu gestor de ventana a instalar - (WM)\n " 14 60 14)

options=(1 "> i3wm | Disponible <"
         2 "> bspwm | Disponible <"
         3 "> dwm | Disponible <"
         4 "> awesome | Disponible <"
         5 "> openbox | Disponible <")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        1)  
            WM="i3wm"
            ;;

        2)
            WM="bspwm"
            ;;

        3)
            WM="dwm"
            ;;

        4)
            WM="awesome"
            ;;

        5)
            WM="openbox"
            ;;
    esac
done
#FINAL (WM)
            ;;
            

        3)
          seleccionTTY=true
          tty="tty"
          ;;


    esac
done

sectionenv=1

}






installenvironment () {


case $environment in 

  "tty")
  echo "" 
  echo "Se esta instalando el entorno TTY:" 
  echo "" 
  arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"

  ;;

  "Xfce4 Arcris")
  echo "" 
  echo "Se esta instalando el entorno Xfce4:" 
  echo "" 

  arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xfce4 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xfce4-goodies --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay mugshot --noeditmenu --noconfirm --needed"
 
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay plata-theme-bin --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gtk-engine-murrine --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-roboto --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay pavucontrol --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gedit --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gedit-plugins --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay plank --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay plank-theme-namor --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay android-file-transfer android-tools android-udev msmtp libmtp libcddb gvfs gvfs-afc gvfs-smb gvfs-gphoto2 gvfs-mtp gvfs-goa gvfs-nfs gvfs-google gst-libav dosfstools f2fs-tools ntfs-3g udftools nilfs-utils polkit gpart mtools cifs-utils --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay wget unzip zip --noeditmenu --noconfirm --needed"

  clear

  arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/themexfce4/master/configxfce4.zip -P /home/$username/"
  # arch-chroot /mnt /bin/bash -c "rm -r /home/$username/.config"
  ls --all /home/$username
  echo ""
  sleep 10
  arch-chroot /mnt /bin/bash -c "unzip -o /home/$username/configxfce4.zip -d /home/$username/"
  arch-chroot /mnt /bin/bash -c "rm /home/$username/configxfce4.zip"
  arch-chroot /mnt /bin/bash -c "chown -R $username:users /home/$username/.config/"
  echo ""
  sleep 10

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-webkit2-greeter --noeditmenu --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/themexfce4/master/glorius.zip -P /home/$username/"
echo ""
sleep 10
arch-chroot /mnt /bin/bash -c "unzip -o /home/$username/glorius.zip -d /usr/share/lightdm-webkit/themes/"
arch-chroot /mnt /bin/bash -c "rm /home/$username/glorius.zip"

sed -i 's/^webkit_theme\s*=\s*\(.*\)/webkit_theme = glorious #\1/g' /mnt/etc/lightdm/lightdm-webkit2-greeter.conf
sed -i 's/^debug_mode\s*=\s*\(.*\)/debug_mode = true #\1/g' /mnt/etc/lightdm/lightdm-webkit2-greeter.conf
sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-webkit2-greeter/g' /mnt/etc/lightdm/lightdm.conf

# Comprimir un directorio
# zip sampleZipFile.zip -r /sampleZip/ExampleDir

# para sobreescribir archivos
# unzip -o sampleZipFile.zip 

# Descomprimir un archivo a un directorio diferente
# unzip sampleZipFile.zip -d /usr/sampleZip/ExampleDir

  ;;


  "Xfce4")
  echo "" 
  echo "Se esta instalando el entorno Xfce4:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xfce4 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xfce4-goodies --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay mugshot --noeditmenu --noconfirm --needed"
 
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;



  "Gnome")
  echo "" 
  echo "Se esta instalando el entorno Gnome:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-shell --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-shell-extensions --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay chrome-gnome-shell --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay webp-pixbuf-loader --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-tweaks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-themes-extra --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable gdm"

  ;;


  "Gnome Lite")
  echo "" 
  echo "Se esta instalando el entorno Gnome:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-shell --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-control-center --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-tweaks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-terminal --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay nautilus --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-keyring --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable gdm"

  ;;



  "Gnome Arcris")
  echo "" 
  echo "Se esta instalando el entorno Gnome Arcris:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-shell --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-control-center --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-tweaks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-terminal --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay nautilus --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-keyring --noeditmenu --noconfirm --needed"

  # THEME ####################
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-shell-extensions  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-menus --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay chrome-gnome-shell --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-system-monitor --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay papirus-icon-theme --noeditmenu --noconfirm --needed"
  ############################

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable gdm"



arch-chroot /mnt /bin/bash -c "sudo -u $username yay android-file-transfer android-tools android-udev msmtp libmtp libcddb gvfs gvfs-afc gvfs-smb gvfs-gphoto2 gvfs-mtp gvfs-goa gvfs-nfs gvfs-google gst-libav dosfstools f2fs-tools ntfs-3g udftools nilfs-utils polkit gpart mtools cifs-utils --noeditmenu --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "sudo -u $username yay wget unzip zip --noeditmenu --noconfirm --needed"

clear

arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/themegnome/master/config_gnome.zip -P /home/$username/"
arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/themegnome/master/local_gnome.zip -P /home/$username/"
arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/themegnome/master/theme_gnome.zip -P /home/$username/"
ls /home/$username
echo ""
sleep 10
arch-chroot /mnt /bin/bash -c "unzip -o /home/$username/config_gnome.zip -d /home/$username/"
arch-chroot /mnt /bin/bash -c "unzip -o /home/$username/local_gnome.zip -d /home/$username/"
arch-chroot /mnt /bin/bash -c "unzip -o /home/$username/theme_gnome.zip -d /home/$username/"
arch-chroot /mnt /bin/bash -c "rm /home/$username/config_gnome.zip"
arch-chroot /mnt /bin/bash -c "rm /home/$username/local_gnome.zip"
arch-chroot /mnt /bin/bash -c "rm /home/$username/theme_gnome.zip"
arch-chroot /mnt /bin/bash -c "chown -R $username:users /home/$username/.config/"
arch-chroot /mnt /bin/bash -c "chown -R $username:users /home/$username/.local/"
arch-chroot /mnt /bin/bash -c "chown -R $username:users /home/$username/.themes/"
echo ""
sleep 10

# Comprimir un directorio
# zip sampleZipFile.zip -r /sampleZip/ExampleDir

# para sobreescribir archivos
# unzip -o sampleZipFile.zip 

# Descomprimir un archivo a un directorio diferente
# unzip sampleZipFile.zip -d /usr/sampleZip/ExampleDir


  ;;




  "KDE Plasma")
  echo "" 
  echo "Se esta instalando el entorno KDE Plasma:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay plasma --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay kde-applications --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay konsole --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay konqueror --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay dolphin --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay discover --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay latte-dock --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay bluedevil --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay kate --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay kdialog --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay keditbookmarks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay kwrite --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay appmenu-gtk-module --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libdbusmenu-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libdbusmenu-gtk3 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libdbusmenu-gtk2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay kfind --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay khelpcenter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay kscreen --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay powerdevil --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay kdeconnect --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay kdegraphics-thumbnailers --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay sddm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libxcb --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay qt5-virtualkeyboard --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable sddm"

  ;;


"KDE Plasma Lite")
  echo "" 
  echo "Se esta instalando el entorno KDE Plasma:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  plasma --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  dolphin --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  konsole --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  discover --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  sddm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  libxcb --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  qt5-virtualkeyboard --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username pacman -S  libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable sddm"

  ;;



"Deepin")
  echo "" 
  echo "Se esta instalando el entorno Deepin:" 
  echo "" 
arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay deepin --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay deepin-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter-settings  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay light-locker  --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay poppler-glib --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libgsf --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm.service"

  ;;


"MATE")
  echo "" 
  echo "Se esta instalando el entorno MATE:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay mate --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay mate-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay mate-applet-dock --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay mate-menu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay brisk-menu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay libcanberra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay mate-power-manager --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay mate-media --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay system-config-printer --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;


"LXQt")
  echo "" 
  echo "Se esta instalando el entorno LXQt:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxqt --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay arc-gtk-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xscreensaver --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay connman --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxqt-connman-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay connman-gtk --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay sddm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "systemctl enable sddm"
  arch-chroot /mnt /bin/bash -c "systemctl enable connman"
  arch-chroot /mnt /bin/bash -c "systemctl disable NetworkManager"

  ;;



"LXDE")
  echo "" 
  echo "Se esta instalando el entorno LXDE:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxde --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxmed --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay slock --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "systemctl enable lxdm"

  ;;



"LXDE GTK3")
  echo "" 
  echo "Se esta instalando el entorno LXDE GTK3:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxde-gtk3 --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay slock --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "systemctl enable lxdm"

  ;;



"Budgie")
  echo "" 
  echo "Se esta instalando el entorno Budgie:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay budgie-desktop --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay budgie-screensaver --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-control-center --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-tweaks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay tilix --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay nautilus --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;


"Cinnamon")
  echo "" 
  echo "Se esta instalando el entorno Cinnamon:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay cinnamon --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay slock --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay cinnamon-translations --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxterminal --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay numlockx --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-slick-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

clear
echo ""
touch /mnt/etc/lightdm/slick-greeter.conf
tee /mnt/etc/lightdm/slick-greeter.conf <<EOF
[Greeter]
background=/usr/share/backgrounds/arcris.png
stretch-background-across-monitors=true
show-hostname=false
show-a11y=false
show-power=false
activate-numlock=true
background-color=#0000
draw-user-backgrounds=true
icon-theme-name=Adwaita
EOF

sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-slick-greeter/g' /mnt/etc/lightdm/lightdm.conf





  ;;



"GNOME 2")
  echo "" 
  echo "Se esta instalando el entorno GNOME 2:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-flashback --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-backgrounds --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-control-center --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-applets --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay sensors-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay metacity --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-control-center --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-tweaks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxterminal --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay nautilus --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay light-locker --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;



"Enlightenment")
  echo "" 
  echo "Se esta instalando el entorno Enlightenment:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay enlightenment --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay entrance-git --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay terminology --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay eluminance-git --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay stalonetray --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxterminal --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-inconsolata --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-font-awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay noto-fonts-emoji --noeditmenu --noconfirm --needed"
  
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable entrance"

  ;;


"i3wm")
  echo "" 
  echo "Se esta instalando el entorno i3wm:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay i3-gaps --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay i3blocks --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay i3lock --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay i3status --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"

  ;;



"bspwm")
  echo "" 
  echo "Se esta instalando el entorno bspwm:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay bspwm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay sxhkd --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"
  
  ;;


"dwm")
  echo "" 
  echo "Se esta instalando el entorno dwm:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay dwm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"
  
  ;;



"awesome")
  echo "" 
  echo "Se esta instalando el entorno Awesome:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"
  
  ;;



"openbox")
  echo "" 
  echo "Se esta instalando el entorno Open box:" 
  echo "" 

arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-server --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
  # arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay openbox --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay obconf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxappearance-obconf --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxinput --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxrandr --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay obkey --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay obapps --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ob-autostart --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay dmenu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rofi --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay st --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay rxvt-unicode --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ly --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay pcmanfm --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay tumbler --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbs --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ffmpegthumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay raw-thumbnailer --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay freetype2 --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay network-manager-applet --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay polkit-gnome --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-keyring  --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-hack --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnu-free-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay awesome-terminal-fonts --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-dejavu --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay ttf-liberation --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay papirus-icon-theme --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay gnome-themes-extra --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay lxappearance --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay feh --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay xclip --noeditmenu --noconfirm --needed"
  arch-chroot /mnt /bin/bash -c "sudo -u $username yay maim --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "sudo -u $username yay accountsservice --noeditmenu --noconfirm --needed"

  arch-chroot /mnt /bin/bash -c "systemctl enable ly"
  
  ;;




esac

}